Mysql:
  DBType: mysql
  Username: root
  Password: 123456
  Host: 120.46.91.53:3306
  DBName: guiding
  TablePrefix: guiding_
  Charset: utf8
  ParseTime: True
  MaxIdle: 10
  MaxOpen: 30
Redis:
  Address: 121.36.86.143:6379 # redis 服务器地址
  DB: 0 # redis 数据库索引（0-15）
  Password: JCT1005kn. # 认证密码
  PoolSize: 100 # redis 连接池大小
  CacheTime: 10m # redis 缓存时间
Token:
  Key: tqgymXijyHpZbeoXcOexVBHbBsBlDNrm # 密钥（必须是32个字节，因为我们使用的是 chacha20poly1305 加密算法）
  UserTokenDuration: 24h # 用户 token 的有效期限
  AccountTokenDuration: 720h # 账户 token 的有效期限
  AuthorizationKey: Authorization
  AuthorizationType: Bearer